export default {
  subscriptions: {
    TRAINEE_ADDED: 'TRAINEE_ADDED',
    TRAINEE_UPDATED: 'TRAINEE_UPDATED',
    TRAINEE_DELETED: 'TRAINEE_DELETED',
    USER_ADDED: 'USER_ADDED',
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',
  },
};